repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/pycqa/pylint
    rev: v2.15.0
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]
        additional_dependencies: [Flask, keras, numpy, Pillow, tensorflow, pytest]
